spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?characterEncoding=UTF-8&zeroDateTimeBehavior=round&useSSL=true&servertTimezone=UTC
    username: root
    password: root
  mvc:
    static-path-pattern: /**


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8099

file:
  root:
    path: D:/ceshi/travle/src/main/resources/static/images

